# Generated by Django 4.0.2 on 2022-04-21 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(default='', max_length=200, verbose_name='Job Name')),
                ('dateAdded', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time')),
                ('isCompleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoListItem',
        ),
    ]
